from __future__ import annotations

# ruff: noqa: E501
from typing import Any

AGENTIC_MATURITY_STAGES: list[dict[str, Any]] = [
    {
        "id": 1,
        "name": "No or near-zero AI",
        "plain_english_summary": "You mostly work without AI, or only use it occasionally like a search box.",
        "how_it_feels": "AI is optional and not part of your daily workflow.",
        "what_the_human_does": "Writes, edits, decides, and executes everything manually.",
        "what_the_agent_does": "Very little or nothing beyond one-off answers.",
        "trust_level": "Low",
        "autonomy_level": "None",
        "risk": "Low operational risk, but low speed gains.",
        "example_workflow": "Ask a chatbot for ideas, then do all work yourself.",
        "evidence_of_this_level": "No file editing, no tool permissions, no loops.",
        "next_step_to_level_up": "Try a supervised IDE assistant that can suggest or edit code with your approval.",
    },
    {
        "id": 2,
        "name": "Supervised IDE agent",
        "plain_english_summary": "AI helps inside the editor, but you approve almost every meaningful action.",
        "how_it_feels": "Faster drafting with frequent checkpoints.",
        "what_the_human_does": "Approves edits, runs tests, and keeps full control.",
        "what_the_agent_does": "Suggests patches and small steps in context.",
        "trust_level": "Cautious",
        "autonomy_level": "Low",
        "risk": "Low to medium; mistakes are usually caught by review.",
        "example_workflow": "Ask IDE agent to refactor a function, then inspect diff before applying.",
        "evidence_of_this_level": "Human gates most changes and commands.",
        "next_step_to_level_up": "Allow short autonomous bursts (YOLO mode) on low-risk tasks.",
    },
    {
        "id": 3,
        "name": "IDE YOLO mode",
        "plain_english_summary": "You let the IDE agent act with fewer approvals for quick progress.",
        "how_it_feels": "Much faster, with occasional surprises.",
        "what_the_human_does": "Sets guardrails and reviews outcomes after runs.",
        "what_the_agent_does": "Executes multi-step edits and commands with light supervision.",
        "trust_level": "Moderate",
        "autonomy_level": "Medium",
        "risk": "Medium; speed rises but so does chance of hidden regressions.",
        "example_workflow": "Agent updates several files, runs tests, and returns a summary.",
        "evidence_of_this_level": "Fewer prompts and approvals per task.",
        "next_step_to_level_up": "Move from isolated edits to broader conversations over full diffs.",
    },
    {
        "id": 4,
        "name": "Wide IDE agent / diff review",
        "plain_english_summary": "You collaborate over larger codebase changes and review broader diffs.",
        "how_it_feels": "AI becomes a teammate for bigger chunks of work.",
        "what_the_human_does": "Steers intent, validates architecture, and approves final diff.",
        "what_the_agent_does": "Touches many related files and explains rationale.",
        "trust_level": "Moderate to high",
        "autonomy_level": "Medium",
        "risk": "Medium; context breadth can introduce subtle coupling mistakes.",
        "example_workflow": "Conversation-driven refactor across routes, tests, and docs.",
        "evidence_of_this_level": "Frequent full-diff discussions before merge.",
        "next_step_to_level_up": "Adopt CLI-first agent runs for repeatable task execution.",
    },
    {
        "id": 5,
        "name": "CLI-first single agent",
        "plain_english_summary": "You run one agent from terminal workflows with explicit tasks and logs.",
        "how_it_feels": "More operational and reproducible.",
        "what_the_human_does": "Defines task boundaries, monitors run logs, and intervenes when needed.",
        "what_the_agent_does": "Plans and executes a task loop in a bounded environment.",
        "trust_level": "High for bounded tasks",
        "autonomy_level": "Medium to high",
        "risk": "Medium to high depending on permissions.",
        "example_workflow": "Agent receives objective, uses tools, and stops on explicit conditions.",
        "evidence_of_this_level": "Traceable runs with action/observation history.",
        "next_step_to_level_up": "Split work into multiple specialist agents.",
    },
    {
        "id": 6,
        "name": "Parallel agents",
        "plain_english_summary": "You run several agents at once, each handling a distinct part of the task.",
        "how_it_feels": "Parallel throughput with coordination overhead.",
        "what_the_human_does": "Defines responsibilities and merges outputs.",
        "what_the_agent_does": "Works concurrently on scoped subtasks.",
        "trust_level": "Task-dependent",
        "autonomy_level": "High",
        "risk": "High if outputs conflict or assumptions diverge.",
        "example_workflow": "One agent drafts, one critiques, one gathers references in parallel.",
        "evidence_of_this_level": "Multiple active agents per objective.",
        "next_step_to_level_up": "Build repeatable playbooks for managing larger swarms.",
    },
    {
        "id": 7,
        "name": "Hand-managed agent swarm (10+)",
        "plain_english_summary": "You manually coordinate many agents for ambitious tasks.",
        "how_it_feels": "Powerful but cognitively heavy.",
        "what_the_human_does": "Acts as dispatcher, reviewer, and conflict resolver.",
        "what_the_agent_does": "Executes specialized work packets at scale.",
        "trust_level": "Selective",
        "autonomy_level": "Very high",
        "risk": "Very high operational complexity and drift risk.",
        "example_workflow": "A human manages many agent threads across product, code, docs, and QA.",
        "evidence_of_this_level": "10+ active agent workstreams managed by one person.",
        "next_step_to_level_up": "Create a custom orchestrator so coordination is systematized.",
    },
    {
        "id": 8,
        "name": "Custom orchestrator",
        "plain_english_summary": "A purpose-built system coordinates specialist agents, policies, and verification.",
        "how_it_feels": "Agent operations become a platform, not just ad-hoc prompting.",
        "what_the_human_does": "Designs orchestration rules, risk controls, and success metrics.",
        "what_the_agent_does": "Coordinates multi-agent plans with evaluator checkpoints.",
        "trust_level": "Governed trust",
        "autonomy_level": "Programmable high autonomy",
        "risk": "High blast radius without strong policy, logging, and rollback.",
        "example_workflow": "Orchestrator routes tasks to planner/critic/writer agents then verifies before release.",
        "evidence_of_this_level": "Persistent orchestration logic, telemetry, and policy gates.",
        "next_step_to_level_up": "Continuously improve governance, auditability, and safety instrumentation.",
    },
]


ASSESSMENT_QUESTIONS = [
    "Do you only ask AI questions manually?",
    "Do you let AI edit files?",
    "Do you review every command?",
    "Do you run agents in the terminal?",
    "Do you run more than one agent at once?",
    "Do you use an orchestrator?",
]
