const el = (id) => document.getElementById(id);
const buttons = el('buttons'), log = el('log'), apiState = el('api-state'), meta = el('meta');
const useCaseOptions = el('use-case-options'), selectionLabel = el('selection-label'), confirmBtn = el('confirm-btn');
const downloadArtifactBtn = el('download-artifact'), useCaseModal = el('use-case-modal'), modalTitle = el('modal-title');
const modalBody = el('modal-body'), modalCloseBtn = el('modal-close'), contextInput = el('context-input');
const theatreSteps = el('theatre-steps'), replayBtn = el('replay-btn'), replayState = el('replay-state'), taskboardEl = el('taskboard');
const scorePanel = el('score-panel'), beforeAfter = el('before-after');
const mobileViewBtn = el('mobile-view-btn'), desktopViewBtn = el('desktop-view-btn');
const previewTools = document.querySelector('.preview-tools');
let quizAnswers = Array(8).fill(false);
let selectedUseCase = null, confirmedUseCase = null, selectedUseCaseContext = '', latestArtifact = null, runInProgress = false, lastReplaySteps = [], theatreCards = [];
const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const createEl = (tag, cls, text) => { const n = document.createElement(tag); if (cls) n.className = cls; if (text) n.textContent = text; return n; };
const setStatus = (label, type = '') => { apiState.innerHTML = `<span class="pill ${type}">${label}</span>`; };
const pretty = (v, fallback = 'Available after run') => (v === undefined || v === null || v === '' ? fallback : String(v));
function clearRunPanels() { scorePanel.innerHTML=''; theatreSteps.innerHTML=''; taskboardEl.innerHTML=''; replayState.textContent=''; replayBtn.disabled=true; theatreCards=[]; }
function appendMessage(role, text){ const item=createEl('div',`msg ${role}`,text); item.setAttribute('data-role', role); log.appendChild(item); log.scrollTop=log.scrollHeight; }
function clearOutput(msg='Choose a level to watch a simulated agent workflow. The output is a read-only trace; you only need to choose the scenario and level.'){ log.innerHTML=''; appendMessage('system', msg); meta.textContent='Run a level to verify API path, model and request id.'; setStatus('Waiting'); latestArtifact=null; downloadArtifactBtn.disabled=true; clearRunPanels(); }
function updateLevelButtonsVisibility(){ buttons.classList.toggle('hidden', !confirmedUseCase); }
function renderUseCases(data){ useCaseOptions.textContent=''; Object.entries(data).forEach(([key,text], i)=>{ const b=createEl('button','option'); b.innerHTML=`<strong>${i+1}. ${key.replaceAll('_',' ')}</strong><div class="muted">${text.split('.')[0]}.</div><span class="pill">Select scenario</span>`; b.onclick=()=>{ selectedUseCase=key; confirmedUseCase=null; confirmBtn.disabled=false; selectionLabel.textContent=`Selected (not confirmed): ${key.replaceAll('_',' ')}`; document.querySelectorAll('.option').forEach((o)=>o.classList.remove('active')); b.classList.add('active'); clearOutput('Use case changed. Confirm direction to continue.'); updateLevelButtonsVisibility(); }; b.ondblclick=()=>{ modalTitle.textContent=`Use case context: ${key.replaceAll('_',' ')}`; modalBody.textContent=text; useCaseModal.classList.remove('hidden');}; useCaseOptions.appendChild(b); });}
function renderScorePanel(agenticness, data){ if(!agenticness){scorePanel.innerHTML=''; return;} const sim=data?.yegge_simulation||{}; const fields=[['Capability score',`${agenticness.capability_score ?? data?.score_summary?.capability_score ?? data?.level ?? 'Available after run'}/10`],['Agenticness score',`${agenticness.agenticness_score ?? agenticness.score ?? 'Available after run'}/10`],['Yegge alignment score',`${agenticness.yegge_alignment_score ?? 'Available after run'}/10`],['Closest Yegge stage',pretty(agenticness.closest_yegge_stage||sim.closest_yegge_stage)],['Why this maps to Yegge',pretty(sim.why_this_maps_to_yegge||agenticness.yegge_alignment_explanation,'Workshop-safe simulation mapping shown after run')],['Why this is not production',pretty(sim.why_not_production,'Workshop-safe simulation')],['Capability being taught',pretty(sim.capability_being_taught)],['Simulated environment',pretty(sim.simulated_environment,'Workshop-safe simulation')]]; scorePanel.innerHTML=''; fields.forEach(([k,v])=>{ const c=createEl('article','score-card'); c.innerHTML=`<strong>${k}</strong><div>${v}</div>`; scorePanel.appendChild(c); }); }
function renderTheatre(data){ theatreSteps.innerHTML=''; theatreCards=[]; const steps=data.theatre_steps||[]; steps.forEach((s)=>{ const card=createEl('article','theatre-step'); const actor=(s.actor||'agent').toLowerCase(); card.innerHTML=`<div class="section-header"><span class="actor">${actor}</span><span class="pill ${s.status||'complete'}">${s.status||'complete'}</span></div><strong>${s.label||'Step'}</strong><div>${s.summary||''}</div><div class="muted">${s.detail||''}</div>`; theatreCards.push(card); theatreSteps.appendChild(card); }); lastReplaySteps=(data.replay_steps?.length?data.replay_steps:steps.map((s)=>s.summary||s.label)).filter(Boolean); replayBtn.disabled=!lastReplaySteps.length; }
function normalizeStatus(raw){ const value=(raw||'pending').toString().toLowerCase().replace(/^taskstatus\./,'').replace(/_/g,' ').trim(); if(value.includes('needs human review')) return 'needs_human_review'; if(value.includes('merge')) return 'merged'; if(value.includes('run')) return 'running'; if(value.includes('complete')) return 'completed'; if(value.includes('fail')) return 'failed'; return 'pending'; }
function summarizeOutput(output){ if(!output) return 'No output yet.'; return String(output).slice(0, 180); }
function renderTaskboard(data){ taskboardEl.innerHTML=''; const board=data?.taskboard; if(!board){ taskboardEl.innerHTML='<p class="muted">Run Level 8 to see the orchestrator dashboard.</p>'; return; }
  const records = Array.isArray(board) ? board : (Array.isArray(board.workers) ? board.workers : []);
  if(!records.length){ taskboardEl.innerHTML='<p class="muted">Run Level 8 to see the orchestrator dashboard.</p>'; return; }
  const normalized = records.map((r) => ({
    worker_name: r.worker_name || r.worker || 'Worker',
    worker_role: r.worker_role || r.role || 'agent',
    task: r.task || 'No task description',
    status: normalizeStatus(r.status),
    worker_status: normalizeStatus(r.worker_status || r.status),
    attempt: r.attempt || 1,
    output: summarizeOutput(r.output || r.output_summary || r.summary),
    error: r.error || '',
  }));
  const columns=['pending','running','completed','needs_human_review','merged','failed'];
  const wrap=createEl('div','taskboard-grid');
  columns.forEach((status)=>{ const col=createEl('section','taskboard-column'); col.innerHTML=`<h4>${status.replaceAll('_',' ')}</h4>`; normalized.filter((r)=>r.status===status).forEach((w)=>{ const wc=createEl('article',`worker-card ${w.status}`); wc.innerHTML=`<strong>${w.worker_name}</strong><div class="muted">${w.worker_role}</div><div>Task: ${w.task}</div><div>Status: ${w.status} · Worker: ${w.worker_status}</div><div>Attempt: ${w.attempt}</div><div>Output: ${w.output}</div>${w.error?`<div class="pill blocked">Error: ${w.error}</div>`:''}`; col.appendChild(wc); }); if(!col.querySelector('.worker-card')) col.innerHTML += '<div class="muted">No workers in this state.</div>'; wrap.appendChild(col); });
  taskboardEl.appendChild(wrap);
}
function renderQuiz(){ const q=el('quiz-questions'); const qs=['Only prompt AI','AI edits files','You approve every action','AI runs tools','Terminal agents','Multiple agents','Taskboard review','Own orchestration system']; q.innerHTML=''; qs.forEach((t,i)=>{ const c=createEl('article','quiz-card segmented-card'); c.innerHTML=`<strong>${i+1}. ${t}</strong><div class="segmented" role="group" aria-label="${t}"><button type="button" class="seg-btn ${!quizAnswers[i]?'active':''}" data-q="${i}" data-v="0" aria-pressed="${!quizAnswers[i]}">No</button><button type="button" class="seg-btn ${quizAnswers[i]?'active':''}" data-q="${i}" data-v="1" aria-pressed="${quizAnswers[i]}">Yes</button></div>`; q.appendChild(c);}); q.onclick=(e)=>{ const b=e.target.closest('.seg-btn'); if(!b) return; const i=Number(b.dataset.q); quizAnswers[i]=b.dataset.v==='1'; renderQuiz(); renderAssessmentResult(); }; renderAssessmentResult(); }
function renderAssessmentResult(){ const v=quizAnswers.map(Boolean); let stage=1; if(v[7]) stage=8; else if(v[5]||v[6]) stage=6+(v[6]?1:0); else if(v[3]||v[4]) stage=4+(v[4]?1:0); else if(v[1]&&v[2]) stage=3; else if(v[0]) stage=2; const conf = stage>=6?'high':'medium'; const risk = stage>=6?'Risk warning: keep strict verifier and approval gates before any merge decisions.':'Risk warning: avoid over-trusting outputs without checks.'; const next = stage<4?'Next safe step: supervised edits with explicit approval.' : stage<7?'Next safe step: bounded tool use with verification.' : 'Next safe step: tighten merge policy and rollback checks.'; el('assessment-result').textContent=`You are probably around Stage ${stage}. Confidence: ${conf}. ${risk} ${next} Try Glytch Level ${Math.min(8,stage+1)} next.`; }
function renderBeforeAfter(levels){ beforeAfter.innerHTML=''; Object.entries(levels).forEach(([id,l])=>{ const c=createEl('article','card'); c.innerHTML=`<h3>Level ${id}: ${l.name}</h3><p><strong>Before:</strong> ${l.before||'Raw model capability.'}</p><p><strong>Agentic:</strong> ${l.agentic||'Adds checks, approval, and traceable decisions.'}</p>`; beforeAfter.appendChild(c); }); }
function setForcedView(mode){ const nextMode = mode === 'mobile' ? 'mobile' : 'desktop'; document.body.classList.remove('force-mobile','force-desktop'); document.body.classList.add(nextMode === 'mobile' ? 'force-mobile' : 'force-desktop'); mobileViewBtn.classList.toggle('active', nextMode==='mobile'); desktopViewBtn.classList.toggle('active', nextMode==='desktop'); mobileViewBtn.setAttribute('aria-pressed', String(nextMode==='mobile')); desktopViewBtn.setAttribute('aria-pressed', String(nextMode==='desktop')); try { window.localStorage.setItem('glytch:view-mode', nextMode); } catch (_) {} }
async function init(){ clearOutput(); const [l,u,m]=await Promise.all([fetch('/api/levels'),fetch('/api/use-cases'),fetch('/api/agentic-maturity')]); const levels=await l.json(), useCases=await u.json(), maturity=await m.json(); renderUseCases(useCases.use_cases||{}); (maturity.stages||[]).forEach((s)=>{ const c=createEl('article','card'); c.innerHTML=`<strong>Stage ${s.id}: ${s.name}</strong><div class="muted">${s.plain_english_summary||''}</div>`; el('maturity-cards').appendChild(c);}); renderQuiz(); renderBeforeAfter(levels.levels||{});
 Object.entries(levels.levels||{}).forEach(([k,v])=>{ const b=createEl('button','level-card'); b.innerHTML=`<strong>Level ${k}: ${v.name}</strong><span>${v.description||''}</span><span class="muted">Run to inspect workflow</span><span class="pill">Workshop-safe</span>`; b.onclick=()=>runLevel(Number(k)); buttons.appendChild(b);}); updateLevelButtonsVisibility(); }
async function runLevel(level){ /* unchanged simplified */ if(!confirmedUseCase || runInProgress) return; runInProgress=true; setStatus('Running…'); clearRunPanels(); log.innerHTML=''; appendMessage('system','Running simulation. No answer needed.'); try{ const res=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({level,use_case:confirmedUseCase,use_case_context:selectedUseCaseContext})}); const data=await res.json(); const backend=data.backend||{}; setStatus(backend.configured&&res.ok?'OpenAI API Connected':'OpenAI API Not Connected', backend.configured&&res.ok?'ok':'err'); meta.textContent=`request_id=${data.request_id||'n/a'} · provider=${backend.provider||'n/a'} · model=${backend.model||'n/a'}`; if(!res.ok){ log.innerHTML=''; appendMessage('system',`Request failed (${res.status}): ${data.error||'unknown error'}`); return; } renderScorePanel(data.agenticness, data); renderTheatre(data); renderTaskboard(data); const lines=data.lines||['No output lines returned.']; log.innerHTML=''; appendMessage('trace','This is the agent workflow trace. You do not need to type a response.'); for(const line of lines){ appendMessage('trace',line); await sleep(prefersReducedMotion?0:120);} latestArtifact=`Glytch Export\nGenerated: ${new Date().toISOString()}\nLevel: ${level}\nUse case: ${confirmedUseCase}\n\n${lines.join('\n')}`; downloadArtifactBtn.disabled=false; } finally { runInProgress=false; }}
el('start-btn').onclick=()=>{ el('entry').classList.add('hidden'); el('app').classList.remove('hidden'); };
confirmBtn.onclick=()=>{ if(!selectedUseCase) return clearOutput('Select a use case before confirming direction.'); selectedUseCaseContext=contextInput.value.trim(); confirmedUseCase=selectedUseCase; selectionLabel.textContent=`Confirmed direction: ${selectedUseCase.replaceAll('_',' ')}${selectedUseCaseContext?` | context: ${selectedUseCaseContext}`:''}`; clearOutput('Direction confirmed. Choose a level to run.'); updateLevelButtonsVisibility(); };
replayBtn.onclick=async()=>{ if(!lastReplaySteps.length||runInProgress) return; replayBtn.disabled=true; for(let i=0;i<lastReplaySteps.length;i++){ theatreCards.forEach((c)=>c.classList.remove('active-replay')); theatreCards[i]?.classList.add('active-replay'); appendMessage('system',`Replay: ${lastReplaySteps[i]}`); await sleep(prefersReducedMotion?0:300);} replayBtn.disabled=false; replayState.textContent='Replay finished'; };
downloadArtifactBtn.onclick=()=>{ if(!latestArtifact) return; const blob=new Blob([latestArtifact],{type:'text/plain;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=createEl('a'); a.href=url; a.download=`glytch-artifact-${new Date().toISOString().slice(0,10)}.txt`; document.body.append(a); a.click(); a.remove(); URL.revokeObjectURL(url); };
modalCloseBtn.onclick=()=>useCaseModal.classList.add('hidden');
const debug = new URLSearchParams(window.location.search).get('debug') === '1';
if (!debug && previewTools) previewTools.classList.add('hidden');
const systemDefaultMode = window.matchMedia('(max-width: 759px)').matches ? 'mobile' : 'desktop';
let savedMode = null; try { savedMode = window.localStorage.getItem('glytch:view-mode'); } catch (_) {}
setForcedView(savedMode || systemDefaultMode);
mobileViewBtn.onclick=()=>setForcedView('mobile'); desktopViewBtn.onclick=()=>setForcedView('desktop');
init();
