const el = (id) => document.getElementById(id);
const buttons = el('buttons'), log = el('log'), apiState = el('api-state'), meta = el('meta');
const useCaseOptions = el('use-case-options'), selectionLabel = el('selection-label'), confirmBtn = el('confirm-btn');
const downloadArtifactBtn = el('download-artifact'), useCaseModal = el('use-case-modal'), modalTitle = el('modal-title');
const modalBody = el('modal-body'), modalCloseBtn = el('modal-close'), contextInput = el('context-input');
const theatreSteps = el('theatre-steps'), replayBtn = el('replay-btn'), replayState = el('replay-state'), taskboardEl = el('taskboard');
const scorePanel = el('score-panel'), beforeAfter = el('before-after');
const mobileViewBtn = el('mobile-view-btn'), desktopViewBtn = el('desktop-view-btn');
const previewTools = document.querySelector('.preview-tools');
let quizAnswers = Array(8).fill(false);
let selectedUseCase = null, confirmedUseCase = null, selectedUseCaseContext = '', latestArtifact = null, runInProgress = false, lastReplaySteps = [], theatreCards = [];
const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const createEl = (tag, cls, text) => { const n = document.createElement(tag); if (cls) n.className = cls; if (text !== undefined && text !== null) n.textContent = text; return n; };
const pretty = (v, fallback = 'Available after run') => (v === undefined || v === null || v === '' ? fallback : String(v));
const safeScore = (v, fallback = 'Available after run') => Number.isFinite(Number(v)) ? `${Number(v)}/10` : fallback;
const setStatus = (label, type = '') => { apiState.textContent = ''; const pill = createEl('span', `pill ${type}`.trim(), label); apiState.appendChild(pill); };
const appendKV = (parent, label, value) => { const d = createEl('div'); d.appendChild(createEl('strong', '', `${label}: `)); d.appendChild(document.createTextNode(value)); parent.appendChild(d); };
function clearRunPanels() { scorePanel.textContent=''; theatreSteps.textContent=''; taskboardEl.textContent=''; replayState.textContent=''; replayBtn.disabled=true; theatreCards=[]; }
function appendMessage(role, text){ const item=createEl('div',`msg ${role}`,text); item.setAttribute('data-role', role); log.appendChild(item); log.scrollTop=log.scrollHeight; }
function clearOutput(msg='Choose a level to watch a simulated agent workflow. The output is a read-only trace; you only need to choose the scenario and level.'){ log.textContent=''; appendMessage('system', msg); meta.textContent='Run a level to verify API path, model and request id.'; setStatus('Waiting'); latestArtifact=null; downloadArtifactBtn.disabled=true; clearRunPanels(); }
function updateLevelButtonsVisibility(){ buttons.classList.toggle('hidden', !confirmedUseCase); }
function renderUseCases(data){ useCaseOptions.textContent=''; Object.entries(data).forEach(([key,text], i)=>{ const b=createEl('button','option'); b.type='button'; b.append(createEl('strong','',`${i+1}. ${key.replaceAll('_',' ')}`), createEl('div','muted',`${text.split('.')[0]}.`), createEl('span','pill','Select scenario')); b.onclick=()=>{ selectedUseCase=key; confirmedUseCase=null; confirmBtn.disabled=false; selectionLabel.textContent=`Selected (not confirmed): ${key.replaceAll('_',' ')}`; document.querySelectorAll('.option').forEach((o)=>o.classList.remove('active')); b.classList.add('active'); clearOutput('Use case changed. Confirm direction to continue.'); updateLevelButtonsVisibility(); }; b.ondblclick=()=>{ modalTitle.textContent=`Use case context: ${key.replaceAll('_',' ')}`; modalBody.textContent=text; useCaseModal.classList.remove('hidden');}; useCaseOptions.appendChild(b); });}
function renderScorePanel(agenticness, data){ scorePanel.textContent=''; if(!agenticness) return; const sim=data?.yegge_simulation||{}; const fields=[['Capability score',safeScore(agenticness.capability_score ?? data?.score_summary?.capability_score),'Capability score = what AI behaviour is being demonstrated'],['Agenticness score',safeScore(agenticness.agenticness_score ?? agenticness.score),'Agenticness score = how much workflow control/autonomy surrounds it'],['Yegge alignment score',safeScore(agenticness.yegge_alignment_score,'Not applicable to this level'),'Yegge alignment = how closely this simulates the matching Yegge stage']];
 fields.forEach(([k,v,e])=>{ const c=createEl('article','score-card'); c.append(createEl('strong','',k), createEl('div','',v), createEl('div','muted',e)); scorePanel.appendChild(c); });
 [['Closest Yegge stage',pretty(agenticness.closest_yegge_stage||sim.closest_yegge_stage,'Workshop-safe simulation')],['Why this maps to Yegge',pretty(sim.why_this_maps_to_yegge||agenticness.yegge_alignment_explanation,'Workshop-safe simulation mapping shown after run')],['Why this is not production',pretty(sim.why_not_production,'Workshop-safe simulation')]].forEach(([k,v])=>{ const c=createEl('article','score-card'); c.append(createEl('strong','',k), createEl('div','',v)); scorePanel.appendChild(c); }); }
function renderTheatre(data){ theatreSteps.textContent=''; theatreCards=[]; const steps=data.theatre_steps||[]; steps.forEach((s)=>{ const card=createEl('article',`theatre-step ${normalizeStatus(s.status)}`); const header=createEl('div','section-header'); header.append(createEl('span','actor',(s.actor||'agent').toLowerCase()), createEl('span',`pill ${normalizeStatus(s.status)}`,normalizeStatus(s.status))); card.append(header, createEl('strong','',s.label||'Step'), createEl('div','',s.summary||''), createEl('div','muted',s.detail||'')); theatreCards.push(card); theatreSteps.appendChild(card); }); lastReplaySteps=(data.replay_steps?.length?data.replay_steps:steps.map((s)=>s.summary||s.label)).filter(Boolean); replayBtn.disabled=!lastReplaySteps.length; }
function normalizeStatus(raw){ const value=(raw||'pending').toString().toLowerCase().replace(/^taskstatus\./,'').trim(); if(value.includes('needs human review')||value.includes('needs_human_review')||value.includes('needs review')) return 'needs_human_review'; if(value.includes('merge')) return 'merged'; if(value.includes('run')) return 'running'; if(value.includes('complete')) return 'completed'; if(value.includes('approve')) return 'approved'; if(value.includes('block')) return 'blocked'; if(value.includes('fail')) return 'failed'; return 'pending'; }
function summarizeOutput(output){ if(!output) return 'No output yet.'; return String(output).slice(0, 180); }
function renderTaskboard(data){ taskboardEl.textContent=''; const board=data?.taskboard; const records = Array.isArray(board) ? board : (Array.isArray(board?.workers) ? board.workers : []); if(!records.length){ taskboardEl.appendChild(createEl('p','muted','Run Level 8 to see the orchestrator dashboard.')); return; }
 const normalized = records.map((r) => ({worker_name: r.worker_name || r.worker || 'Worker',worker_role: r.worker_role || r.role || 'agent',task: r.task || 'No task description',status: normalizeStatus(r.status),worker_status: normalizeStatus(r.worker_status || r.status),attempt: r.attempt || 1,output: summarizeOutput(r.output || r.output_summary || r.summary),error: r.error || ''}));
 const columns=['pending','running','completed','needs_human_review','merged','failed']; const wrap=createEl('div','taskboard-grid');
 columns.forEach((status)=>{ const col=createEl('section','taskboard-column'); col.appendChild(createEl('h4','',status.replaceAll('_',' '))); normalized.filter((r)=>r.status===status).forEach((w)=>{ const wc=createEl('article',`worker-card ${w.status}`); appendKV(wc,'Worker',w.worker_name); appendKV(wc,'Role',w.worker_role); appendKV(wc,'Task',w.task); appendKV(wc,'Status',`${w.status} · Worker: ${w.worker_status}`); appendKV(wc,'Attempt',String(w.attempt)); appendKV(wc,'Output',w.output); if(w.error) wc.appendChild(createEl('div','pill blocked',`Error: ${w.error}`)); col.appendChild(wc); }); if(!col.querySelector('.worker-card')) col.appendChild(createEl('div','muted','No workers in this state.')); wrap.appendChild(col); });
 taskboardEl.appendChild(wrap);
 const approval=data?.approval_summary||{}; const panel=createEl('section','panel approval-panel'); panel.appendChild(createEl('h4','', 'Approval and merge summary')); appendKV(panel,'Verifier result',pretty(approval.verifier_result,'Available after run')); appendKV(panel,'Approval required',pretty(approval.approval_required,'Available after run')); appendKV(panel,'Approved for merge',pretty(approval.approved,'Available after run')); appendKV(panel,'Merge decision',pretty(approval.merge_decision,'Available after run')); appendKV(panel,'Merge policy',pretty(approval.merge_policy,'Workshop-safe simulation')); appendKV(panel,'Final status',pretty(data?.stage_summary?.name,'Workshop-safe simulation')); const decision = String(approval.merge_decision||'').toLowerCase(); panel.appendChild(createEl('p','muted', decision.includes('approved') ? 'Merged after verifier and approval gate.' : 'Needs human review — merge blocked by verifier or approval gate.')); taskboardEl.appendChild(panel);
}
function renderQuiz(){ const q=el('quiz-questions'); const qs=['Only prompt AI','AI edits files','You approve every action','AI runs tools','Terminal agents','Multiple agents','Taskboard review','Own orchestration system']; q.textContent=''; qs.forEach((t,i)=>{ const c=createEl('article','quiz-card segmented-card'); c.appendChild(createEl('strong','',`${i+1}. ${t}`)); const seg=createEl('div','segmented'); seg.setAttribute('role','group'); seg.setAttribute('aria-label',t); const no=createEl('button',`seg-btn ${!quizAnswers[i]?'active':''}`,'No'); no.type='button'; no.dataset.q=String(i); no.dataset.v='0'; no.setAttribute('aria-pressed', String(!quizAnswers[i])); const yes=createEl('button',`seg-btn ${quizAnswers[i]?'active':''}`,'Yes'); yes.type='button'; yes.dataset.q=String(i); yes.dataset.v='1'; yes.setAttribute('aria-pressed', String(quizAnswers[i])); seg.append(no, yes); c.appendChild(seg); q.appendChild(c);}); q.onclick=(e)=>{ const b=e.target.closest('.seg-btn'); if(!b) return; const i=Number(b.dataset.q); quizAnswers[i]=b.dataset.v==='1'; renderQuiz(); renderAssessmentResult(); }; renderAssessmentResult(); }
function renderAssessmentResult(){ el('assessment-result').textContent='Workshop-safe simulation maturity estimate generated from your selections.'; }
function renderBeforeAfter(levels){ beforeAfter.textContent=''; Object.entries(levels).forEach(([id,l])=>{ const c=createEl('article','card'); c.append(createEl('h3','',`Level ${id}: ${l.name}`), createEl('p','',`Before: ${l.before||'Raw model capability.'}`), createEl('p','',`Agentic: ${l.agentic||'Adds checks, approval, and traceable decisions.'}`)); beforeAfter.appendChild(c); }); }
async function runLevel(level){ if(!confirmedUseCase || runInProgress) return; runInProgress=true; setStatus('Running…','running'); clearRunPanels(); log.textContent=''; appendMessage('system','Running simulation. No answer needed.');
 try{ const res=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({level,use_case:confirmedUseCase,use_case_context:selectedUseCaseContext})}); let data; try { data=await res.json(); } catch { throw new Error('Malformed response payload'); }
 const backend=data?.backend||{}; setStatus(backend.configured&&res.ok?'OpenAI API Connected':'OpenAI API Not Connected', backend.configured&&res.ok?'ok':'err'); meta.textContent=`request_id=${data?.request_id||'Available after run'} · provider=${backend.provider||'Workshop-safe simulation'} · model=${backend.model||'Workshop-safe simulation'}`;
 if(!res.ok){ throw new Error(data?.error || `Backend returned ${res.status}`); }
 renderScorePanel(data.agenticness, data); renderTheatre(data); renderTaskboard(data); const lines=Array.isArray(data.lines)&&data.lines.length?data.lines:['No output lines returned.']; log.textContent=''; appendMessage('trace','Read-only simulation trace. Nothing here requires you to answer.'); for(const line of lines){ appendMessage('trace',line); await sleep(prefersReducedMotion?0:120);} latestArtifact=`Glytch Export\nGenerated: ${new Date().toISOString()}\nLevel: ${level}\nUse case: ${confirmedUseCase}\n\n${lines.join('\n')}`; downloadArtifactBtn.disabled=false; }
 catch(_err){ setStatus('Request failed','failed'); log.textContent=''; appendMessage('system','Something went wrong while running the simulation. No action was taken. Please try again.'); replayBtn.disabled=true; downloadArtifactBtn.disabled=true; }
 finally { runInProgress=false; }}
async function init(){ clearOutput(); const [l,u,m]=await Promise.all([fetch('/api/levels'),fetch('/api/use-cases'),fetch('/api/agentic-maturity')]); const levels=await l.json(), useCases=await u.json(), maturity=await m.json(); renderUseCases(useCases.use_cases||{}); (maturity.stages||[]).forEach((s)=>{ const c=createEl('article','card'); c.append(createEl('strong','',`Stage ${s.id}: ${s.name}`), createEl('div','muted',s.plain_english_summary||'')); el('maturity-cards').appendChild(c);}); renderQuiz(); renderBeforeAfter(levels.levels||{}); Object.entries(levels.levels||{}).forEach(([k,v])=>{ const b=createEl('button','level-card'); b.type='button'; b.append(createEl('strong','',`Level ${k}: ${v.name}`), createEl('span','',v.description||''), createEl('span','muted','Run to inspect workflow'), createEl('span','pill','Workshop-safe')); b.onclick=()=>runLevel(Number(k)); buttons.appendChild(b);}); updateLevelButtonsVisibility(); }
el('start-btn').onclick=()=>{ el('entry').classList.add('hidden'); el('app').classList.remove('hidden'); };
confirmBtn.onclick=()=>{ if(!selectedUseCase) return clearOutput('Select a use case before confirming direction.'); selectedUseCaseContext=contextInput.value.trim(); confirmedUseCase=selectedUseCase; selectionLabel.textContent=`Confirmed direction: ${selectedUseCase.replaceAll('_',' ')}${selectedUseCaseContext?` | context: ${selectedUseCaseContext}`:''}`; clearOutput('Direction confirmed. Choose a level to run.'); updateLevelButtonsVisibility(); };
replayBtn.onclick=async()=>{ if(!lastReplaySteps.length||runInProgress) return; replayBtn.disabled=true; for(let i=0;i<lastReplaySteps.length;i++){ theatreCards.forEach((c)=>c.classList.remove('active-replay')); theatreCards[i]?.classList.add('active-replay'); appendMessage('system',`Replay: ${lastReplaySteps[i]}`); await sleep(prefersReducedMotion?0:300);} replayBtn.disabled=false; replayState.textContent='Replay finished'; };
downloadArtifactBtn.onclick=()=>{ if(!latestArtifact) return; const blob=new Blob([latestArtifact],{type:'text/plain;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=createEl('a'); a.href=url; a.download=`glytch-artifact-${new Date().toISOString().slice(0,10)}.txt`; document.body.append(a); a.click(); a.remove(); URL.revokeObjectURL(url); };
modalCloseBtn.onclick=()=>useCaseModal.classList.add('hidden');
document.addEventListener('keydown', (e)=>{ if(e.key==='Escape') useCaseModal.classList.add('hidden'); });
const debug = new URLSearchParams(window.location.search).get('debug') === '1'; if (!debug && previewTools) previewTools.hidden = true;
init();
